### guests
GET https://my-wedding-jnur.onrender.com/guests
X-API-Key: {{apiKey}}

### guests localhost
GET http://localhost:8080/guests
X-API-Key: {{apiKey}}

### guests summary localhost
GET http://localhost:8080/guests/summary
X-API-Key: {{apiKey}}

### guests summary
GET https://my-wedding-jnur.onrender.com/guests/summary
X-API-Key: {{apiKey}}
